// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsINOWDiuf_A7srryvuNajYQwxae3Dqy0',
    appId: '1:795453323864:web:20c99e15c9d0a610d1a82d',
    messagingSenderId: '795453323864',
    projectId: 'auth-af04a',
    authDomain: 'auth-af04a.firebaseapp.com',
    storageBucket: 'auth-af04a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx9ahm61yv_C-GR7QjQ4lyMWUAUoTqAjc',
    appId: '1:795453323864:android:72df55cc590dfa76d1a82d',
    messagingSenderId: '795453323864',
    projectId: 'auth-af04a',
    storageBucket: 'auth-af04a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcLdBybTeDWJekbmiL5gJv4mOGvOqAP1k',
    appId: '1:795453323864:ios:5252aa3e1626a2d4d1a82d',
    messagingSenderId: '795453323864',
    projectId: 'auth-af04a',
    storageBucket: 'auth-af04a.appspot.com',
    iosBundleId: 'com.example.myFirstFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcLdBybTeDWJekbmiL5gJv4mOGvOqAP1k',
    appId: '1:795453323864:ios:5252aa3e1626a2d4d1a82d',
    messagingSenderId: '795453323864',
    projectId: 'auth-af04a',
    storageBucket: 'auth-af04a.appspot.com',
    iosBundleId: 'com.example.myFirstFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsINOWDiuf_A7srryvuNajYQwxae3Dqy0',
    appId: '1:795453323864:web:a202d40054c00ac5d1a82d',
    messagingSenderId: '795453323864',
    projectId: 'auth-af04a',
    authDomain: 'auth-af04a.firebaseapp.com',
    storageBucket: 'auth-af04a.appspot.com',
  );

}